site_name: caselaw
site_url: https://cyrii42.github.io/caselaw
repo_url: https://github.com/cyrii42/caselaw
repo_name: cyrii42/caselaw
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    # - navigation.tracking
    # - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.footnote.tooltips
    # - content.code.annotation
    # - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: cyan

plugins:
  # - social
  - search

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji 
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  
copyright: |
  &copy; 2024 <a href="mailto:zvaughan@bm.net"  target="_blank" rel="noopener">Zachary M. Vaughan</a>