site_name: FCRA & Related Law
site_url: https://cyrii42.github.io/caselaw
repo_url: https://github.com/cyrii42/caselaw
repo_name: cyrii42/caselaw

nav:
  # - Intro: index.md
  - Fair Credit Reporting Act: 
    - index.md
    - FCRA Statute: fcra/statute.md
    - Maximum Possible Accuracy: fcra/max_accuracy.md
    - Reinvestigations: fcra/reinvestigations.md
    - Willfulness: fcra/willfulness.md
    - Damages: fcra/damages.md
    # - FCRA-Specific Class Certification Decisions: fcra/class_cert.md
  - Class Certification: 
    - class_cert/index.md
    - Fed. R. Civ. P. 23: class_cert/rule23.md
    - Numerosity: class_cert/numerosity.md
    - Commonality: class_cert/commonality.md
    - Typicality: class_cert/typicality.md
    - Adequacy of Representation: class_cert/adequacy.md
    - Ascertainability: class_cert/ascertainability.md
    - Rule 23(b) Types:
      - class_cert/23b3_types/index.md
      - (b)(1) - Inconsistent Adjudications: class_cert/23b3_types/23b1.md
      - (b)(2) - Injunctive Relief: class_cert/23b3_types/23b2.md
      - (b)(3) - Predominance: class_cert/23b3_types/23b3.md
  - Article III Standing: 
    - standing/index.md
    - FCRA Cases: standing/fcra.md
    - FDCPA Cases: standing/fdcpa.md
theme:
  name: material
  font: 
    text: Source Sans 3 # Mate # Roboto # Source Serif 4  # PT Serif # Source Sans 3
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
  palette:
  
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      # primary: blue

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      # primary: red
      # accent: amber 
      
extra:
  social:
    - icon: material/web
      link: https://bergermontague.com/attorneys/zach-vaughan/
    - icon: material/email
      link: mailto:zvaughan@bm.net
    - icon: fontawesome/brands/github
      link: https://github.com/cyrii42/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zvaughan/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zvaughan/

    
    

  
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline 
    #     name: Switch to dark mode
    #   primary: red
    #   accent: amber 
    # - scheme: slate 
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode    
    #   primary: blue
      # accent: cyan

plugins:
  # - social
  - search

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji 
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css
  
copyright: |
  &copy; 2024 <a href="mailto:zvaughan@bm.net"  target="_blank" rel="noopener">Zachary M. Vaughan</a>