site_name: Consumer Law
site_url: https://cyrii42.github.io/caselaw
repo_url: https://github.com/cyrii42/caselaw
repo_name: cyrii42/caselaw

nav:
  - index.md
  
  - Fair Credit Reporting Act: 
    # - fcra/index.md
    - Statutory Excerpts: fcra/statute.md
    - Consumer Reporting Agencies: fcra/cra.md
    - Maximum Possible Accuracy: fcra/max_accuracy.md
    - Reinvestigations: fcra/reinvestigations.md
    - Willfulness: fcra/willfulness.md
    - Damages: fcra/damages.md
    - Class Cert: fcra/class_cert.md
    - Standing: fcra/standing.md
    - State Analogues: fcra/states.md

  # - FDCPA:
  #   # - fdcpa/index.md
  #   - Statutory Excerpts: fdcpa/statute.md
  #   - Damages: fdcpa/damages.md
  #   - Class Cert: fdcpa/class_cert.md
  #   - Standing: fdcpa/standing.md
  #   - State Analogues: fdcpa/states.md
    
  # - TCPA:
  #   # - tcpa/index.md
  #   - Statutory Excerpts: tcpa/statute.md
  #   - Damages: tcpa/damages.md
  #   - Class Cert: tcpa/class_cert.md
  #   - Standing: tcpa/standing.md
  #   - State Analogues: tcpa/states.md
    
  # - State Consumer Law:
  #   - New York:
  #   - New Jersey:
  #   - California: 
  #   - Illinois:
  #   - Maryland:
  #   - Massachusetts:
  #   - Michigan:
  #   - Minnesota:
  #   - Pennsylvania:
  #   - Oregon:
  #   - Washington: 
    
  - Class Cert: 
    # - class_cert/index.md
    - Fed. R. Civ. P. 23: class_cert/rule23.md
    - Numerosity: class_cert/numerosity.md
    - Commonality: class_cert/commonality.md
    - Typicality: class_cert/typicality.md
    - Adequacy of Representation: class_cert/adequacy.md
    - Ascertainability: class_cert/ascertainability.md
    - Predominance: class_cert/predominance.md
    # - Rule 23(b) Types:
    #   - (b)(1) - Inconsistent Adjudications: class_cert/23b3_types/23b1.md
    #   - (b)(2) - Injunctive Relief: class_cert/23b3_types/23b2.md
    #   - (b)(3) - Predominance: class_cert/23b3_types/23b3.md
    
  - Standing: 
    # - standing/index.md
    - FCRA Cases: standing/fcra.md
    - FDCPA Cases: standing/fdcpa.md
    
  - Arbitration:
    # - arbitration/index.md
    - Federal Arbitration Act: arbitration/faa.md
    
theme:
  name: material
  font: 
    text: Source Serif 4  # Mate # Roboto # Source Serif 4  # PT Serif # Source Sans 3
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
  palette:
  
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      # primary: red
      # accent: amber 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      # primary: blue
      # accent: cyan
  
  #     # Palette toggle for automatic mode
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/brightness-auto
  #       name: Switch to dark mode

  #   # Palette toggle for dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
  #     # primary: blue

  #   # Palette toggle for light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default 
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #     # primary: red
  #     # accent: amber 
      
extra:
  social:
    - icon: material/web
      link: https://bergermontague.com/attorneys/zach-vaughan/
    - icon: material/email
      link: mailto:zvaughan@bm.net
    - icon: fontawesome/brands/github
      link: https://github.com/cyrii42/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zvaughan/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zvaughan/

plugins:
  # - social
  - search
  - privacy:
      links_attr_map:
        target: _blank

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji 
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css
  
copyright: |
  &copy; 2024 <a href="mailto:zvaughan@bm.net"  target="_blank" rel="noopener">Zachary M. Vaughan</a>